const items = [
    {
        id: '001',
        image: 'images/1.jpg',
        company: 'SKDK',
        item_name: 'Gym gloves',
        original_price: 1045,
        current_price: 606,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id: '002',
        image: 'images/2.webp',
        company: 'KEVIN LEVRONE',
        item_name: 'Creatine',
        original_price: 10000,
        current_price: 9000,
        discount_percentage: 10,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '003',
        image: 'images/3.jpg',
        company: 'LIFE FITNESS',
        item_name: 'Rubber dumbles',
        original_price: 1599,
        current_price: 495,
        discount_percentage: 69,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '004',
        image: 'images/4.jpg',
        company: 'DYMATIZE',
        item_name: 'Mass gainer',
        original_price: 29999,
        current_price: 29999,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '005',
        image: 'images/5.jpg',
        company: 'BPI',
        item_name: 'Bulk Muscle',
        original_price: 15000,
        current_price: 1500,
        discount_percentage: 10,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '006',
        image: 'images/6.webp',
        company: 'PROSCIENCE',
        item_name: 'Creatine',
        original_price: 10000,
        current_price: 10000,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 0.0,
            count: 0,
        },
    },
    {
        id: '007',
        image: 'images/7.jpg',
        company: 'LIFE FITNESS',
        item_name: 'Hand Gripper',
        original_price: 1599,
        current_price: 639,
        discount_percentage: 60,
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    {
        id: '008',
        image: 'images/8.jpeg',
        company: 'SHAHKIFITNESS',
        item_name: 'Gym West',
        original_price: 1500,
        current_price: 150,
        discount_percentage: 10,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 52000,
        },
    }
];